package com.peekr.core.strings

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    // Navigation
    val home: String,
    val archive: String,
    val tools: String,
    val settings: String,
    val back: String,

    // Feed
    val appName: String,
    val noContentYet: String,
    val connectAccountsOrRefresh: String,
    val refreshNow: String,
    val allPlatforms: String,
    val markAllRead: String,
    val syncInProgress: String,
    val errorOccurred: String,
    val close: String,
    val openLink: String,
    val save: String,

    // Settings
    val settingsTitle: String,
    val contentSection: String,
    val appearanceSection: String,
    val securitySection: String,
    val connectedAccounts: String,
    val connectedAccountsDesc: String,
    val apiKeys: String,
    val apiKeysDesc: String,
    val security: String,
    val securityDesc: String,
    val backup: String,
    val backupDesc: String,
    val eventLogs: String,
    val eventLogsDesc: String,
    val themeTitle: String,
    val followSystem: String,
    val lightMode: String,
    val darkMode: String,
    val language: String,
    val chooseTheme: String,

    // Accounts
    val connectedAccountsTitle: String,
    val connectAccountsHint: String,
    val connect: String,
    val manage: String,
    val disconnect: String,
    val disconnectConfirmTitle: String,
    val disconnectConfirmBody: String,
    val deleteAll: String,
    val cancel: String,
    val connectedLabel: String,
    val linksAdded: String,

    // YouTube
    val youtubeLinkTitle: String,
    val youtubeLinkHint: String,
    val addedChannels: String,
    val addChannelLabel: String,
    val channelUrlLabel: String,
    val channelPlaceholder: String,
    val add: String,
    val done: String,
    val edit: String,
    val delete: String,
    val editLinkLabel: String,
    val saveEdit: String,
    val checking: String,
    val channelFound: String,
    val channelNotFound: String,
    val addApiKeyFirst: String,

    // RSS
    val rssTitle: String,
    val rssHint: String,
    val addedFeeds: String,
    val feedUrlLabel: String,
    val feedPlaceholder: String,

    // API Keys
    val apiKeysTitle: String,
    val apiKeysInfo: String,
    val platformStatus: String,
    val connected: String,
    val notConnected: String,
    val keyMissing: String,
    val saveKeys: String,
    val savedSuccess: String,
    val testConnection: String,
    val testing: String,
    val connectionOk: String,
    val connectionFailed: String,
    val fromWebsite: String,

    // Telegram
    val telegramApiMissing: String,
    val addApiFirst: String,
    val goToApiKeys: String,
)

val ArabicStrings = AppStrings(
    home = "الرئيسية",
    archive = "الأرشيف",
    tools = "الأدوات",
    settings = "الإعدادات",
    back = "رجوع",

    appName = "Peekr",
    noContentYet = "لا يوجد محتوى بعد",
    connectAccountsOrRefresh = "اربط حساباتك من الإعدادات أو اضغط تحديث",
    refreshNow = "تحديث الآن",
    allPlatforms = "الكل",
    markAllRead = "تحديد الكل كمقروء",
    syncInProgress = "جاري التزامن...",
    errorOccurred = "حدث خطأ",
    close = "إغلاق",
    openLink = "فتح الرابط",
    save = "حفظ",

    settingsTitle = "الإعدادات",
    contentSection = "المحتوى",
    appearanceSection = "المظهر",
    securitySection = "الأمان والنظام",
    connectedAccounts = "ربط الحسابات",
    connectedAccountsDesc = "تليجرام، يوتيوب، واتساب، فيسبوك، RSS",
    apiKeys = "مفاتيح API",
    apiKeysDesc = "إدارة مفاتيح المنصات المختلفة",
    security = "الأمان والخصوصية",
    securityDesc = "قفل التطبيق، PIN، بصمة الإصبع",
    backup = "النسخ الاحتياطي",
    backupDesc = "تصدير، استيراد، جوجل درايف",
    eventLogs = "سجل الأحداث",
    eventLogsDesc = "عرض الأخطاء والتحذيرات",
    themeTitle = "المظهر",
    followSystem = "حسب النظام",
    lightMode = "الوضع الفاتح",
    darkMode = "الوضع الداكن",
    language = "اللغة",
    chooseTheme = "اختر المظهر",

    connectedAccountsTitle = "ربط الحسابات",
    connectAccountsHint = "اربط حساباتك للبدء في متابعة المحتوى",
    connect = "ربط",
    manage = "إدارة",
    disconnect = "قطع",
    disconnectConfirmTitle = "قطع الاتصال؟",
    disconnectConfirmBody = "سيتم حذف جميع الروابط المضافة",
    deleteAll = "حذف الكل",
    cancel = "إلغاء",
    connectedLabel = "✓ متصل",
    linksAdded = "روابط مضافة",

    youtubeLinkTitle = "إضافة قنوات يوتيوب",
    youtubeLinkHint = "أضف رابط القناة — التغييرات تُحفظ تلقائياً",
    addedChannels = "القنوات المضافة",
    addChannelLabel = "إضافة قناة",
    channelUrlLabel = "رابط أو اسم القناة",
    channelPlaceholder = "youtube.com/c/channelname",
    add = "إضافة",
    done = "تم ✓",
    edit = "تعديل",
    delete = "حذف",
    editLinkLabel = "تعديل الرابط",
    saveEdit = "حفظ",
    checking = "جاري التحقق...",
    channelFound = "✓ تم التحقق من القناة",
    channelNotFound = "✗ القناة غير موجودة",
    addApiKeyFirst = "أضف YouTube API Key أولاً للتحقق",

    rssTitle = "إضافة RSS Feed",
    rssHint = "أضف رابط الـ RSS — التغييرات تُحفظ تلقائياً",
    addedFeeds = "الـ Feeds المضافة",
    feedUrlLabel = "رابط RSS",
    feedPlaceholder = "https://example.com/feed",

    apiKeysTitle = "مفاتيح API",
    apiKeysInfo = "المفاتيح تُحفظ مشفرة على جهازك ويمكن تغييرها في أي وقت",
    platformStatus = "حالة المنصات",
    connected = "متصل",
    notConnected = "غير متصل",
    keyMissing = "مفتاح مفقود",
    saveKeys = "حفظ المفاتيح",
    savedSuccess = "✓ تم الحفظ",
    testConnection = "اختبار الاتصال",
    testing = "جاري الاختبار...",
    connectionOk = "✓ الاتصال ناجح",
    connectionFailed = "✗ فشل الاتصال",
    fromWebsite = "من موقع",

    telegramApiMissing = "يجب إضافة API ID و API Hash أولاً",
    addApiFirst = "أضف المفاتيح في إعدادات API أولاً",
    goToApiKeys = "الذهاب لمفاتيح API",
)

val EnglishStrings = AppStrings(
    home = "Home",
    archive = "Archive",
    tools = "Tools",
    settings = "Settings",
    back = "Back",

    appName = "Peekr",
    noContentYet = "No content yet",
    connectAccountsOrRefresh = "Connect your accounts from Settings or tap Refresh",
    refreshNow = "Refresh Now",
    allPlatforms = "All",
    markAllRead = "Mark all as read",
    syncInProgress = "Syncing...",
    errorOccurred = "An error occurred",
    close = "Close",
    openLink = "Open link",
    save = "Save",

    settingsTitle = "Settings",
    contentSection = "Content",
    appearanceSection = "Appearance",
    securitySection = "Security & System",
    connectedAccounts = "Connected Accounts",
    connectedAccountsDesc = "Telegram, YouTube, WhatsApp, Facebook, RSS",
    apiKeys = "API Keys",
    apiKeysDesc = "Manage platform API keys",
    security = "Security & Privacy",
    securityDesc = "App lock, PIN, fingerprint",
    backup = "Backup",
    backupDesc = "Export, import, Google Drive",
    eventLogs = "Event Logs",
    eventLogsDesc = "View errors and warnings",
    themeTitle = "Theme",
    followSystem = "Follow system",
    lightMode = "Light mode",
    darkMode = "Dark mode",
    language = "Language",
    chooseTheme = "Choose Theme",

    connectedAccountsTitle = "Connected Accounts",
    connectAccountsHint = "Connect your accounts to start following content",
    connect = "Connect",
    manage = "Manage",
    disconnect = "Disconnect",
    disconnectConfirmTitle = "Disconnect?",
    disconnectConfirmBody = "All added links will be deleted",
    deleteAll = "Delete All",
    cancel = "Cancel",
    connectedLabel = "✓ Connected",
    linksAdded = "links added",

    youtubeLinkTitle = "Add YouTube Channels",
    youtubeLinkHint = "Add channel URL — changes save automatically",
    addedChannels = "Added Channels",
    addChannelLabel = "Add channel",
    channelUrlLabel = "Channel URL or name",
    channelPlaceholder = "youtube.com/c/channelname",
    add = "Add",
    done = "Done ✓",
    edit = "Edit",
    delete = "Delete",
    editLinkLabel = "Edit link",
    saveEdit = "Save",
    checking = "Verifying...",
    channelFound = "✓ Channel verified",
    channelNotFound = "✗ Channel not found",
    addApiKeyFirst = "Add YouTube API Key first to verify",

    rssTitle = "Add RSS Feed",
    rssHint = "Add RSS URL — changes save automatically",
    addedFeeds = "Added Feeds",
    feedUrlLabel = "RSS URL",
    feedPlaceholder = "https://example.com/feed",

    apiKeysTitle = "API Keys",
    apiKeysInfo = "Keys are encrypted on your device and can be changed at any time",
    platformStatus = "Platform Status",
    connected = "Connected",
    notConnected = "Not connected",
    keyMissing = "Key missing",
    saveKeys = "Save Keys",
    savedSuccess = "✓ Saved",
    testConnection = "Test connection",
    testing = "Testing...",
    connectionOk = "✓ Connection OK",
    connectionFailed = "✗ Connection failed",
    fromWebsite = "From",

    telegramApiMissing = "API ID and API Hash are required",
    addApiFirst = "Add API keys in settings first",
    goToApiKeys = "Go to API Keys",
)

val LocalStrings = compositionLocalOf { ArabicStrings }
